// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function GetGames():Promise<Array<backend.GameSchema>>;

export function LoadSave(arg1:string):Promise<Record<string, string>>;

export function SaveData(arg1:string,arg2:Record<string, string>):Promise<void>;
