// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGames() {
  return window['go']['main']['App']['GetGames']();
}

export function LoadSave(arg1) {
  return window['go']['main']['App']['LoadSave'](arg1);
}

export function SaveData(arg1, arg2) {
  return window['go']['main']['App']['SaveData'](arg1, arg2);
}
